# Generated by Django 4.2.6 on 2023-10-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
    ]
