# Generated by Django 4.2.6 on 2023-10-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0002_alter_agenda_endereco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Contato',
        ),
    ]
