# Generated by Django 4.2.7 on 2023-11-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0005_alter_contato_data_nascimento_alter_contato_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='estado',
            field=models.CharField(choices=[('SP', 'São Paulo'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('ES', 'Espirito Santo')], max_length=2),
        ),
    ]
