# Generated by Django 4.2.6 on 2023-11-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0012_contato_interesse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Interesse',
            new_name='interesses',
        ),
    ]
