# Generated by Django 4.2.6 on 2023-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgendaApp', '0013_rename_interesse_contato_interesses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='interesses',
            new_name='interesse',
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.IntegerField(verbose_name='DDD'),
        ),
    ]
